# Generated by Django 2.1.4 on 2022-12-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artopendoragon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_offense_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_sentiment',
            field=models.FloatField(default=0),
        ),
    ]
